BOARD_WIDTH = 25
BOARD_HEIGHT = 17

INVALID_SPACE = -1
EMPTY_SPACE = 0
RED = 1
GREEN = 4

LEFT = (0, -2)
RIGHT = (0, 2)
UP_RIGHT = (1, 1)
UP_LEFT = (1, -1)
DOWN_RIGHT = (-1, 1)
DOWN_LEFT = (-1, -1)

MOVES = [ LEFT, RIGHT, UP_RIGHT, UP_LEFT, DOWN_LEFT, DOWN_RIGHT ]

MAX_PLAYS = 2000
EXPLORING_MATCHES = 1
MAX_MATCHES = 100

WIN = 1
TIE = 0
LOSS = -1
